### ISSUE TITLE
Implement Sign Verify and missing methods

### ISSUE THREAD

**Issue by StringNick** [zig-bitcoin/libsecp256k1-zig#3]
Implement this example:
https://github.com/rust-bitcoin/rust-secp256k1/blob/59f122dbb6b9d1ef8f1b0b7da97ed8514055e0ae/examples/sign_verify.rs#L3-L50
(It can be just added as function to [main](https://github.com/zig-bitcoin/libsecp256k1-zig/blob/main/src/main.zig))

Also implement missing method in https://github.com/zig-bitcoin/libsecp256k1-zig/blob/27024825e2d21640d405f3d5e8ebc4981c56659e/src/secp256k1.zig#L85
verifyEcdsa

Also implement `Message` type:
https://github.com/rust-bitcoin/rust-secp256k1/blob/59f122dbb6b9d1ef8f1b0b7da97ed8514055e0ae/src/lib.rs#L211
with method:
https://github.com/rust-bitcoin/rust-secp256k1/blob/59f122dbb6b9d1ef8f1b0b7da97ed8514055e0ae/src/lib.rs#L255

**Comment by TropicalDog17** [comment]
Hi, can I work on this issue? I've previously worked on Zig code https://github.com/keep-starknet-strange/ziggy-starkdust/pulls?q=is%3Apr+author%3ATropicalDog17
